FROM golang:1.22    

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY *.go ./
COPY models/*.go ./models/
COPY config/*.go ./config/
COPY controllers/*.go ./controllers/

RUN CGO_ENABLED=0 GOOS=linux go build -o /ijudo_api

CMD ["/ijudo_api"]